version: "0.1"

image: docker.8x8.com:5000/8x8/hyperloop/centos7/python

buildInfo:
  buildName: knox-report

install:
  - pip install -r src/knox/requirements.txt
  - pip install knox
  - yum install -y jq
  - ./functions/install_faas-cli.sh

stages:
  verify:
    syntax:
      - knox --version

  security:
    branch: ^none

  publish:
    artifact:
      sh:
        - cd ./functions/expiry-certificates
        - faas-cli template store pull python3-flask-debian
        - faas-cli template store pull dockerfile
        - faas-cli build -f ./stack.yml --shrinkwrap
      customMessage:
        message: "Certificates expiring in less than 90 days {{output}}"
        sh: "knox store find \\* | jq '.[] | select(.days_to_expire <= 90)'"
        sendTo:
          voRoom: raven-test
        sendOnFail: false
      docker:
        - build 8x8/expirycerts-webui:latest ./functions/expiry-certificates/build/expirycerts-webui
        - build 8x8/fetching-expirycerts:latest ./functions/expiry-certificates/build/fetching-expirycerts
        - push 8x8/expirycerts-webui:latest
        - push 8x8/fetching-expirycerts:latest


  cd:
    enabled: false

notifications:
  email: lance.johnson@8x8.com
  vo:
    channel: "raven-test"




