version: "0.1"

debug: true

image: docker.8x8.com:5000/8x8/hyperloop/centos7/python

buildInfo:
  buildName: knox-report

install:
  - ./functions/install_faas-cli.sh

stages:
  security:
    branch: ^none

  publish:
    artifact:
      sh:
        - cd ./functions/expiry-certificates
        - faas-cli template store pull python3-flask-debian
        - faas-cli template store pull dockerfile
        - faas-cli build -f ./stack.yml --shrinkwrap
      docker:
        - build 8x8/expirycerts-webui:latest ./functions/expiry-certificates/build/expirycerts-webui
        - build 8x8/fetching-expirycerts:latest ./functions/expiry-certificates/build/fetching-expirycerts
        - push 8x8/expirycerts-webui:latest
        - push 8x8/fetching-expirycerts:latest
  acceptance:
    provision:
      customMessage:
        message: "Certificates expiring in less than 90 days \\n {{output}} \\n For more information \\n https://openfaas.es.8x8.com/function/expirycerts-webui"
        sh: "curl -s https://openfaas.es.8x8.com/function/fetching-expirycerts --data 'store find \\*'| jq -r '.[] | select(.days_to_expire <= 90).common_name'"
        sendTo:
          voChannel: "Vault Cert Management (Knox)"
          email: lance.johnson@8x8.com
        sendOnFail: false


notifications:
  email: knox@8x8.com
  vo:
    channel: "Knox"




